/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ex_103;

/**
 *
 * @author oskar
 */
public class AppointmentGUI extends javax.swing.JFrame {

    private AppointmentModell bl = new AppointmentModell();
    public AppointmentGUI() {
        initComponents();
        
        list.setModel(bl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu1 = new javax.swing.JMenu();
        jMAdd = new javax.swing.JMenuItem();
        jMDelete = new javax.swing.JMenuItem();
        jMChange = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();

        jMenu1.setText("Termine");

        jMAdd.setText("Hinzufügen");
        jMAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAddActionPerformed(evt);
            }
        });
        jMenu1.add(jMAdd);

        jMDelete.setText("Löschen");
        jMDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMDeleteActionPerformed(evt);
            }
        });
        jMenu1.add(jMDelete);

        jMChange.setText("Ändern");
        jMChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMChangeActionPerformed(evt);
            }
        });
        jMenu1.add(jMChange);

        jPopupMenu1.add(jMenu1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        list.setBorder(javax.swing.BorderFactory.createTitledBorder("Termine"));
        list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(list);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAddActionPerformed
        AppointmentDlg dialog = new AppointmentDlg(this, true);
        dialog.setVisible(true);
        if(dialog.isOk()){
            bl.add(dialog.getApp());
        }
        
    }//GEN-LAST:event_jMAddActionPerformed

    private void jMDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMDeleteActionPerformed
        bl.delete(list.getSelectedIndex());
        
    }//GEN-LAST:event_jMDeleteActionPerformed

    private void jMChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMChangeActionPerformed
        AppointmentDlg d = new AppointmentDlg(this, true);
        Appointment app = bl.get(list.getSelectedIndex());
        d.change(app);
        d.setVisible(true);
        if(d.isOk()){
            
            bl.change(list.getSelectedIndex(),app);
          
        }
    }//GEN-LAST:event_jMChangeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        System.out.println("hallo");    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppointmentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppointmentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppointmentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppointmentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppointmentGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMAdd;
    private javax.swing.JMenuItem jMChange;
    private javax.swing.JMenuItem jMDelete;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list;
    // End of variables declaration//GEN-END:variables
}
